const express = require('express');
const cors = require('cors');

const app = express();
const PORT = 5000;

app.use(cors());

const clients = [];
const severities = ['info', 'success', 'warning', 'error'];
const titles = {
  info: 'System Update',
  success: 'Task Completed',
  warning: 'Attention Needed',
  error: 'Failure Detected',
};

app.get('/events',(req,res) => {
  // Required headers for SSE
  res.setHeader('Content-Type','text/event-stream');
  res.setHeader('Cache-Control','no-cache');
  res.setHeader('Connection','keep-alive');

  // Flush headers immediately
  res.flushHeaders();

  const clientId = Date.now();

  const newClient = {
    id: clientId,
    res
  };

  clients.push(newClient);

  console.log(`Client connected: ${clientId}. Active clients: ${clients.length}`);

  // Send initial event
  res.write(
    `data: ${JSON.stringify({
      type: 'connected',
      title: 'Connection Established',
      message: 'You are now receiving live server notifications.',
      severity: 'success',
      id: `conn-${clientId}`,
      createdAt: new Date().toISOString()
    })}\n\n`
  );

  req.on('close',() => {
    console.log('Client disconnected:',clientId);

    const index = clients.findIndex(c => c.id === clientId);

    if (index !== -1) {
      clients.splice(index,1);
    }
  });
});

// Broadcast helper
function sendEventToAllClients(data) {
  clients.forEach(client => {
    client.res.write(`data: ${JSON.stringify(data)}\n\n`);
  });
}

// Example: send server update every 2 seconds
let counter = 1;
const TIME_INTERVAL = 5000; // in milliseconds

setInterval(() => {
  const severity = severities[counter % severities.length];
  const payload = {
    type: 'notification',
    id: `evt-${counter}`,
    title: `${titles[severity]} #${counter}`,
    message: `This is a ${severity} notification generated by the SSE server.`,
    severity,
    createdAt: new Date().toISOString(),
  };

  console.log('Sending:', payload);

  sendEventToAllClients(payload);

  counter++;
},TIME_INTERVAL);

app.listen(PORT, () => {
  console.log(`SSE server running on http://localhost:${PORT}`);
});